verbose=false
max_width=120
comment_width=120
tab_spaces=2
fn_call_width=120
struct_lit_width=32
single_line_if_else_max_width=120
trailing_comma="Vertical"
chain_indent="Visual"
chain_one_line_max=120
reorder_imports=true
format_strings=false
hard_tabs=false
wrap_match_arms=false
error_on_line_overflow=false
fn_call_style="Visual"
generics_indent = "Visual"
fn_args_layout = "Visual"
array_layout = "Visual"
struct_layout = "Visual"
control_style = "Rfc"
where_style = "Rfc"
use_small_heuristics = "Off"
where_single_line = true
struct_field_align_threshold = 20